# Generated by Django 4.1.13 on 2025-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
